@host = http://localhost:8080

# `/subjects` Endpoints

# Get all subjects
GET {{host}}/subjects

###

# Get all archived subjects
GET {{host}}/subjects/archived

###

# Get a subject
# GET {{host}}/subjects/{{subjectId}}
GET {{host}}/subjects/1

###

# Create a subject
POST {{host}}/subjects
Content-Type: application/json

{
  "code": "ITEC 116",
  "description": "Lorem ipsum dolor.",
  "sections": [
    {
      "course": "BSIT",
      "year": 4,
      "name": "B",
      "gradeColumns": "[]",
      "students": [
        {
          "studentNumber": "2020111",
          "firstName": "Bob",
          "middleName": "",
          "lastName": "Smith",
          "nameSuffix": "Jr.",
          "course": "BSIT",
          "email": "bob.smithjr@cvsu.edu.ph",
          "contactNumber": "09223456793"
        },
        {
          "studentNumber": "2020112",
          "firstName": "James",
          "middleName": "",
          "lastName": "Dumb",
          "nameSuffix": "II",
          "course": "BSCS",
          "email": "james.dumbii@cvsu.edu.ph",
          "contactNumber": "09223456794"
        }
      ]
    },
    {
      "course": "BSCS",
      "year": 2,
      "name": "A",
      "gradeColumns": "[]",
      "students": [

      ]
    }
  ]
}

###

# Edit a subject
# PUT {{host}}/subjects/{{subjectId}}
PUT {{host}}/subjects/1
Content-Type: application/json

{
  "code": "ITEC 117",
  "description": "Lorem ipsum dolor sit."
}

###

# Archive a subject
# DELETE {{host}}/subjects/{{subjectId}}
DELETE {{host}}/subjects/1
