@host = http://localhost:8080

# `/users` Endpoints
# TODO: These endpoints are for ADMIN only

# Get all users
GET {{host}}/users

###

# Get all archived users
GET {{host}}/users/archived

###

# Get a user
# GET {{host}}/users/{{userId}}
GET {{host}}/users/1

###

# Change role of a user
# PUT {{host}}/users/{{userId}}/role
PUT {{host}}/users/1/role
Content-Type: application/json

{
  "role": "ADMIN"
}

###

# Archive a user
# DELETE {{host}}/users/{{userId}}
DELETE {{host}}/users/1
