@host = http://localhost:8080
@gradeId = 1
@subjectSectionId = 1

# `/subject-sections/{{subjectSectionId}}/grades` ENDPOINTS

# Get all student grades of a particular SubjectSection
GET {{host}}/subject-sections/{{subjectSectionId}}/grades

###

# Get all archived student grades of a particular SubjectSection
GET {{host}}/subject-sections/{{subjectSectionId}}/grades/archived

###

# Get one student grade of a particular SubjectSection
GET {{host}}/subject-sections/{{subjectSectionId}}/grades/{{gradeId}}

###

# Add a student (with grades) for a particular SubjectSection
POST {{host}}/subject-sections/{{subjectSectionId}}/grades
Content-Type: application/json

{
  "gradeRows": "[]",
  "attendances": "[]",
  "studentId": 1
}

###

# Update a student grade of a particular SubjectSection
PUT {{host}}/subject-sections/{{subjectSectionId}}/grades/{{gradeId}}
Content-Type: application/json

{
  "gradeRows": "[]",
  "attendances": "[]",
  "studentId": 1
}

###

# Archive a student grade of a particular SubjectSection
DELETE {{host}}/subject-sections/{{subjectSectionId}}/grades/{{gradeId}}
