@host = http://localhost:8080
@studentId = 1

# `/students` ENDPOINTS

# Get all students
GET {{host}}/students

###

# Get one student
GET {{host}}/students/{{studentId}}

###

# Create a student
POST {{host}}/students
Content-Type: application/json

{
  "studentNumber": "String talaga to, 1-60 characters tapos unique",
  "firstName": "1-60 chars",
  "middleName": "60 max chars",
  "lastName": "1-60 chars",
  "nameSuffix": "60 max chars",
  "email": "150 max chars, unique din",
  "contactNumber": "String talaga to, 30 max chars",
  "courseId": 1
}

###

# Update a student
PUT {{host}}/students/{{studentId}}
Content-Type: application/json

{
  "studentNumber": "202010801",
  "firstName": "Juan",
  "middleName": "",
  "lastName": "Dela Cruz",
  "nameSuffix": "IV",
  "email": "juan.delacruziv@cvsu.edu.ph",
  "contactNumber": "09223456789",
  "courseId": 1
}

###

# Delete a student (Can't delete if there are connected Grades to it)
DELETE {{host}}/students/{{studentId}}
