@host = http://localhost:8080
@subjectSectionId = 1
@subjectId = 1

# `/subjects/{{subjectId}}/sections` ENDPOINTS

# Get all sections of a particular subject
GET {{host}}/subjects/{{subjectId}}/sections

###

# Get all archived sections of a particular subject
GET {{host}}/subjects/{{subjectId}}/sections/archived

###

# Get one section of a particular subject
GET {{host}}/subjects/{{subjectId}}/sections/{{subjectSectionId}}

###

# Add a section in a particular subject
POST {{host}}/subjects/{{subjectId}}/sections
Content-Type: application/json

{
  "gradeColumns": "[]",
  "sectionId": 1
}

###

# Update a section in a particular subject
PUT {{host}}/subjects/{{subjectId}}/sections/{{subjectSectionId}}
Content-Type: application/json

{
  "gradeColumns": "[]",
  "sectionId": 1
}

###

# Archive a section in a particular subject
DELETE {{host}}/subjects/{{subjectId}}/sections/{{subjectSectionId}}
